### ISSUE TITLE
demo can not run with go mod .Default().Link undefined

### ISSUE THREAD

**Issue by sinlov** [GoAdminGroup/example#1]
master e5302db [origin/master] update example, add iframe link

env
```bash
$ go version
go version go1.13.5 darwin/amd64
$ go env 
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

run error log:
```bash
$ go run .
# github.com/GoAdminGroup/example/tables
tables/posts.go:21:28: "github.com/GoAdminGroup/go-admin/template".Default().Link undefined (type "github.com/GoAdminGroup/go-admin/template".Template has no field or method Link)
```

example project use wrong version as `github.com/GoAdminGroup/go-admin v1.1.7`

-`please check out relase code!`
https://github.com/GoAdminGroup/go-admin/blob/v1.1.7/template/components/base.go

now template defined code at
https://github.com/GoAdminGroup/go-admin/blob/master/template/components/base.go#L81

**Comment by chenhg5** [comment]
@sinlov New version will be released maybe tonight or tomorrow, it will be fixed.
