### ISSUE TITLE
default username and password

### ISSUE THREAD

**Issue by joe-getcouragenow** [GoAdminGroup/example#5]
am running outside docker.

I cant fine the default username and password to login in the code or config

??

![Screenshot 2020-09-08 at 09 12 50](https://user-images.githubusercontent.com/59567750/92444664-815cbd00-f1b3-11ea-9d5d-d001f781a315.png)

**Comment by chenhg5** [comment]
username: admin
password: admin

**Comment by joe-getcouragenow** [comment]
thanks you :)

On Tue, Sep 8, 2020 at 9:47 AM cg33 <notifications@github.com> wrote:
>
> username: admin
> password: admin
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Mobile:        +4915231894553
Wire:             joe@winwisely99
Telegram:    http://t.me/gedw99
Email:           joe@getcouragenow.org
